version: "3"

services:
  ApiGateway:
    image: nginx:alpine-slim
    container_name: ZuckererApiGateway
    restart: always
    volumes:
      - ./ApiGateway/html:/usr/share/nginx/html:ro
      - ./ApiGateway/conf/99-apigateway.conf:/etc/nginx/conf.d/99-apigateway.conf:ro
    ports:
      - "8000:80"

  MessageQueue:
    image: rabbitmq:3-management-alpine
    container_name: ZuckererMessageQueue
    restart: always
    volumes:
      - ./MessageQueue/data:/var/lib/rabbitmq
    ports:
      - "8001:15672"
      - "5672:5672"

  ArticleService:
    image: zuckerer-articleservice
    build: ../src/ZuckererWarehouse/ArticleService
    container_name: zuckerer-articleservice
    restart: always
    environment:
      - ASPNETCORE_URLS=http://0.0.0.0:8080
      - ASPNETCORE_ENVIRONMENT=Development

